# Site settings
title: #letsstopawar
author:
  name: 
  email: benjamin.heinrich@gmx.at
description: "#letsstopawar: Redirige a openpetition en 3 segundos"

# Build settings
remote_theme: jekyll/minima
